apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deploy
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx 1.14.2
        name: mynginx
        ports:
        - containerPort: 80
